"""empty message

Revision ID: 72ec79003287
Revises: 
Create Date: 2022-10-31 10:14:13.938514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ec79003287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('banda', sa.String(length=250), nullable=True),
    sa.Column('genero', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=250), nullable=True),
    sa.Column('modelo', sa.String(length=250), nullable=True),
    sa.Column('anoDeSalida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=250), nullable=True),
    sa.Column('marca', sa.String(length=250), nullable=True),
    sa.Column('sistemaOperativo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido', sa.String(length=250), nullable=True),
    sa.Column('gradoAcademico', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=250), nullable=True),
    sa.Column('modelo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipo')
    op.drop_table('empleado')
    op.drop_table('celular')
    op.drop_table('auto')
    op.drop_table('album')
    # ### end Alembic commands ###
